
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 142
#define YY_END_OF_BUFFER 143
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[520] =
    {   0,
        0,    0,  143,  142,    1,  141,  141,  139,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,    1,  139,  140,  138,  138,  138,  138,  138,
      138,  117,  138,  118,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  119,  138,
      138,  120,  121,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  122,  123,  124,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,

      138,  138,  138,  138,  125,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  140,  105,  138,  106,  138,  138,
      107,  138,  108,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  129,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  109,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  110,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      111,  138,  138,  112,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  113,  138,  138,  114,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,

      138,  115,  138,  138,  138,  138,  138,  138,  138,  138,
      116,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,   75,  138,   76,   38,   77,  138,  138,  138,   78,
      138,  138,   79,  138,  138,  138,  138,   81,  138,  138,
      138,   82,   83,  138,  138,  138,  138,  138,  138,  138,
       84,  138,  138,   85,   86,  138,  138,   87,  138,   88,
      128,  138,  138,  138,  138,  138,  138,   89,  138,   90,
       91,   92,  138,   94,  138,   95,  138,  138,  138,  138,
       96,  138,  138,  138,  138,  138,   97,  138,  138,  138,

      138,  138,  138,  138,  138,  138,   98,  138,  138,  138,
      138,   99,  100,  101,  138,  132,  138,  138,  138,  138,
      138,  138,  138,  138,  102,  138,  103,  138,  104,  131,
       55,   56,  138,   57,  138,  135,  138,  138,  138,  138,
      138,  138,   58,  138,  138,  138,  138,   59,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  133,   60,
      138,  138,   61,  138,   93,  138,   62,   63,  138,  138,
      138,  138,   64,   65,   66,   67,  138,  130,  138,  138,
      138,   68,   69,  138,  138,  138,  138,  138,   70,  138,
      138,  138,  138,  138,  138,   71,  138,  138,  138,  138,

       72,  138,  138,  138,   73,  138,  138,  138,   74,  138,
       28,  138,  138,   29,  137,  138,   30,  138,  138,  138,
       31,  138,   32,  138,   33,   34,   35,  138,   36,  138,
      138,   39,   40,   41,   42,   43,  138,  138,   44,  127,
      138,  138,   45,  138,  138,  138,   46,  138,  138,   47,
      126,   48,   49,  138,   50,  138,  138,  138,  138,   51,
       52,   53,   54,  138,  138,   12,   13,   14,   15,   16,
      138,  138,   17,  138,  138,   18,   19,   37,   20,  138,
       21,  138,  138,   22,   23,  138,  138,   24,   25,  138,
      138,  138,  138,   26,   27,   80,  138,    7,    8,  138,

        9,  138,   10,  136,  138,  138,  138,   11,  138,    4,
      138,    5,    6,  138,    2,    3,  138,  134,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    3,    1,    1,    3,
        3,    3,    3,    3,    4,    5,    3,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    3,    3,    3,
        3,    3,    3,    1,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
        3,    1,    3,    3,    1,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,    3,    3,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[59] =
    {   0,
        1,    1,    1,    1,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[521] =
    {   0,
        0,    0,  130, 1064,  127, 1064,  122,   54,   51,   51,
       59,  103,   47,  147,   46,   79,  189,   57,   68,   96,
      104,  128,  140,  139,    0,  155,  232,  274,  191,  106,
      144,  105,  121,   79,   75,    0,  112,  143,  180,  211,
      149,  168,  210,    0,  187,  197,  238,  208,  235,  284,
      201,  223,  243,  243,  261,  264,  327,  256,  257,  256,
      254,  272,  287,  285,  287,  301,  293,  291,    0,  305,
      303,  340,  310,  318,  306,  329,  326,  363,  323,  328,
      334,  332,  335,  359,  371,  369,    0,  372,  359,  364,
      382,  379,  375,  380,  379,  385,  392,  381,  381,  399,

      404,  394,  406,  403,  407,  426,  419,  420,  420,  422,
      430,  431,  419,  440,   68,    0,  438,    0,  440,  434,
        0,  450,    0,  437,  447,  435,  447,  476,  445,  443,
      455,  455,  451,  479,  464,  481,    0,  475,  487,  488,
      488,  487,  475,  495,  482,  494,    0,  499,  498,  501,
      491,  499,  497,  497,  515,  526,  515,  518,  520,  531,
      514,  530,  530,  520,  525,  533,  530,  542,  543,  544,
      545,  530,  538,    0,  535,  551,  553,  559,  566,  561,
      565,  558,  560,  562,    0,  572,  567,  568,  585,  586,
      591,  581,  580,  584,  598,  580,  593,  590,  598,  589,

      602,    0,  585,  592,  594,  603,  603,  600,  610,  626,
        0,  618,  630,  622,  621,  641,  629,  626,  645,  626,
      631,  638,  645,  636,  637,  641,  635,  639,  648,  653,
      666,    0,  671,    0,    0,    0,  663,  674,  666,    0,
      667,  669,  669,  679,  673,  675,  695,  681,  697,  692,
      691,    0,    0,  688,  689,  685,  687,  707,  710,  707,
        0,  696,  717,    0,    0,  718,  707,    0,  710,    0,
        0,  723,  717,  712,  721,  722,  734,    0,  731,    0,
        0,    0,  726,    0,  735,    0,  743,  736,  743,  735,
        0,  754,  753,  741,  742,  750,    0,  763,  767,  757,

      753,  755,  774,  767,  773,  785,    0,  786,  783,  788,
      780,    0,    0,  779,  780,    0,  797,  789,  783,  804,
      787,  801,  804,  802,    0,  790,    0,  807,    0,    0,
        0,    0,  789,    0,  811,    0,  815,  818,  809,  807,
      813,  827,    0,  830,  825,  831,  839,    0,  836,  827,
      836,  846,  847,  835,  836,  838,  850,  857,    0,    0,
      841,  850,    0,  856,    0,  844,    0,    0,  847,  863,
      853,  862,    0,    0,    0,    0,  870,    0,  878,  872,
      864,    0,    0,  886,  874,  877,  891,  888,    0,  898,
      901,  899,  884,  903,  907,  890,  893,  892,  912,  913,

        0,  910,  912,  914,    0,  901,  923,  925,    0,  922,
        0,  917,  927,  917,    0,  931,    0,  931,  944,  928,
        0,  947,    0,  948,    0,    0,    0,  949,    0,  941,
      936,    0,    0,    0,    0,    0,  941,  955,    0,    0,
      949,  962,    0,  944,  960,  941,    0,  964,  965,  952,
        0,    0,    0,  960,    0,  975,  977,  976,  963,    0,
        0,    0,    0,  966,  976,    0,    0,    0,    0,    0,
      990,  995,    0,  994,  980,    0,    0,    0,    0,  998,
        0,  985, 1001,    0,    0,  987,  997,    0,    0,  993,
      999,  993, 1010,    0,    0,    0,  996,    0,    0,  997,

        0, 1000,    0,    0,  994, 1004, 1014,    0, 1019,    0,
     1009,    0,    0, 1015,    0,    0, 1017,    0, 1064,   66
    } ;

static yyconst flex_int16_t yy_def[521] =
    {   0,
      519,    1,  519,  519,  519,  519,  519,  519,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  519,  519,  519,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  519,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,    0,  519
    } ;

static yyconst flex_int16_t yy_nxt[1123] =
    {   0,
        4,    5,    6,    7,    6,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   25,
       32,   25,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   25,   32,   25,   35,   34,
       37,   43,   38,   64,   54,   45,   55,   36,   39,   65,
       40,   56,   46,  115,   41,   42,   57,   74,   75,   47,
      115,   44,   48,   35,   34,   66,   37,   43,   38,   64,
       54,   45,   55,   67,   39,   65,   40,   56,   46,   68,

       41,   42,   57,   74,   75,   47,   76,   44,   48,   49,
       77,   66,  110,   50,   79,  114,   78,   51,   80,   67,
      111,  116,   33,   52,   81,   68,   53,   34,   33,  519,
      519,  519,   76,  519,   82,   49,   77,  519,  110,   50,
       79,  114,   78,   51,   80,   90,  111,  116,   83,   52,
       81,   86,   53,   58,   84,   85,   91,  112,  113,   87,
       82,   59,   92,   88,   60,   93,   89,   61,  117,   94,
       62,   90,  122,   63,   83,   95,  123,   86,  519,   58,
       84,   85,   91,  112,  113,   87,  519,   59,   92,   88,
       60,   93,   89,   61,  117,   94,   62,  118,  122,   63,

       69,   95,  123,  129,  127,  119,   70,   71,   72,  519,
      107,  128,  108,   73,  519,  109,  519,  120,  134,  519,
      121,  124,  125,  118,  142,  143,   69,  519,  135,  129,
      127,  119,   70,   71,   72,  126,  107,  128,  108,   73,
       96,  109,   97,  120,  134,   98,  121,  124,  125,  144,
      142,  143,   99,  100,  135,  130,  131,  132,  519,  133,
      136,  126,  519,  145,  519,  137,   96,  146,   97,  519,
      147,   98,  148,  154,  155,  144,  156,  157,   99,  100,
      101,  130,  131,  132,  102,  133,  136,  103,  104,  145,
      138,  137,  158,  146,  105,  139,  147,  106,  148,  154,

      155,  140,  156,  157,  159,  160,  101,  161,  141,  519,
      102,  519,  164,  103,  104,  519,  138,  165,  158,  166,
      105,  139,  519,  106,  167,  162,  519,  140,  163,  172,
      159,  160,  173,  161,  141,  149,  174,  150,  164,  519,
      175,  151,  176,  165,  177,  166,  181,  182,  152,  168,
      167,  162,  153,  183,  163,  172,  519,  184,  173,  169,
      185,  149,  174,  150,  170,  171,  175,  151,  176,  178,
      177,  179,  181,  182,  152,  168,  186,  187,  153,  183,
      188,  189,  180,  184,  190,  169,  185,  191,  192,  193,
      170,  171,  197,  194,  195,  178,  198,  179,  199,  196,

      200,  203,  186,  187,  204,  205,  188,  189,  180,  201,
      190,  206,  207,  191,  192,  193,  209,  202,  197,  194,
      195,  210,  198,  208,  199,  196,  200,  203,  211,  216,
      204,  205,  212,  214,  217,  201,  215,  206,  207,  218,
      220,  222,  209,  202,  223,  219,  224,  210,  225,  208,
      226,  227,  213,  221,  211,  216,  228,  229,  212,  214,
      217,  230,  215,  231,  232,  218,  220,  222,  236,  237,
      223,  219,  224,  238,  225,  519,  226,  227,  213,  221,
      239,  240,  228,  229,  233,  241,  234,  230,  242,  231,
      232,  243,  244,  245,  236,  237,  248,  249,  246,  238,

      250,  235,  251,  252,  253,  254,  239,  240,  255,  256,
      233,  241,  234,  247,  242,  257,  258,  243,  244,  245,
      259,  260,  248,  249,  246,  261,  250,  235,  251,  252,
      253,  254,  262,  263,  255,  256,  264,  265,  266,  247,
      267,  257,  258,  268,  269,  270,  259,  260,  271,  272,
      273,  261,  274,  275,  276,  277,  279,  280,  262,  263,
      281,  282,  264,  265,  266,  278,  267,  283,  284,  268,
      269,  270,  285,  286,  271,  272,  273,  287,  274,  275,
      276,  277,  279,  280,  288,  289,  281,  282,  290,  291,
      292,  278,  293,  283,  284,  294,  295,  296,  285,  286,

      297,  298,  299,  287,  300,  301,  302,  303,  304,  305,
      288,  289,  306,  307,  290,  291,  292,  308,  293,  309,
      310,  294,  295,  296,  311,  312,  297,  298,  299,  313,
      300,  301,  302,  303,  304,  305,  314,  315,  306,  307,
      316,  320,  318,  308,  319,  309,  310,  321,  322,  317,
      311,  312,  323,  324,  325,  313,  326,  327,  329,  330,
      331,  328,  314,  315,  332,  333,  316,  320,  318,  334,
      319,  335,  336,  321,  322,  317,  337,  338,  323,  324,
      325,  339,  326,  327,  329,  330,  331,  328,  340,  341,
      332,  333,  342,  343,  344,  334,  345,  335,  336,  346,

      347,  348,  337,  338,  349,  350,  351,  339,  352,  353,
      354,  355,  356,  357,  340,  341,  358,  359,  342,  343,
      344,  360,  345,  361,  362,  346,  347,  348,  363,  364,
      349,  350,  351,  365,  352,  353,  354,  355,  356,  357,
      366,  367,  358,  359,  368,  369,  370,  360,  372,  361,
      362,  373,  374,  375,  363,  364,  378,  371,  379,  365,
      376,  377,  380,  381,  382,  383,  366,  367,  384,  385,
      368,  369,  370,  386,  372,  387,  388,  373,  374,  375,
      389,  390,  378,  371,  379,  391,  376,  377,  380,  381,
      382,  383,  392,  393,  384,  385,  394,  395,  396,  386,

      397,  387,  388,  398,  399,  400,  389,  390,  401,  402,
      403,  391,  404,  405,  406,  407,  408,  409,  392,  393,
      410,  411,  394,  395,  396,  412,  397,  413,  414,  398,
      399,  400,  415,  416,  401,  402,  403,  417,  404,  405,
      406,  407,  408,  409,  418,  419,  410,  411,  420,  421,
      422,  412,  423,  413,  414,  424,  425,  426,  415,  416,
      427,  428,  429,  417,  430,  431,  432,  433,  434,  435,
      418,  419,  436,  437,  420,  421,  422,  438,  423,  439,
      440,  424,  425,  426,  441,  442,  427,  428,  429,  443,
      430,  431,  432,  433,  434,  435,  444,  445,  436,  437,

      446,  447,  448,  438,  449,  439,  440,  450,  451,  452,
      441,  442,  453,  454,  455,  443,  456,  457,  458,  459,
      460,  461,  444,  445,  462,  463,  446,  447,  448,  464,
      449,  465,  466,  450,  451,  452,  467,  468,  453,  454,
      455,  469,  456,  457,  458,  459,  460,  461,  470,  471,
      462,  463,  472,  473,  474,  464,  475,  465,  466,  476,
      477,  478,  467,  468,  479,  480,  481,  469,  482,  483,
      484,  485,  486,  487,  470,  471,  488,  489,  472,  473,
      474,  490,  475,  491,  492,  476,  477,  478,  493,  494,
      479,  480,  481,  495,  482,  483,  484,  485,  486,  487,

      496,  497,  488,  489,  498,  499,  500,  490,  501,  491,
      492,  502,  503,  504,  493,  494,  505,  506,  507,  495,
      508,  509,  510,  511,  512,  513,  496,  497,  514,  515,
      498,  499,  500,  516,  501,  517,  518,  502,  503,  504,
      519,  519,  505,  506,  507,  519,  508,  509,  510,  511,
      512,  513,  519,  519,  514,  515,  519,  519,  519,  516,
      519,  517,  518,    3,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519
    } ;

static yyconst flex_int16_t yy_chk[1123] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    8,    8,
        9,   10,    9,   15,   13,   11,   13,  520,    9,   15,
        9,   13,   11,  115,    9,    9,   13,   18,   19,   11,
       35,   10,   11,   34,   34,   16,    9,   10,    9,   15,
       13,   11,   13,   16,    9,   15,    9,   13,   11,   16,

        9,    9,   13,   18,   19,   11,   20,   10,   11,   12,
       20,   16,   30,   12,   21,   32,   20,   12,   21,   16,
       30,   37,   33,   12,   21,   16,   12,    7,    5,    3,
        0,    0,   20,    0,   22,   12,   20,    0,   30,   12,
       21,   32,   20,   12,   21,   24,   30,   37,   22,   12,
       21,   23,   12,   14,   22,   22,   24,   31,   31,   23,
       22,   14,   24,   23,   14,   26,   23,   14,   38,   26,
       14,   24,   41,   14,   22,   26,   42,   23,    0,   14,
       22,   22,   24,   31,   31,   23,    0,   14,   24,   23,
       14,   26,   23,   14,   38,   26,   14,   39,   41,   14,

       17,   26,   42,   46,   45,   39,   17,   17,   17,    0,
       29,   45,   29,   17,    0,   29,    0,   40,   48,    0,
       40,   43,   43,   39,   51,   51,   17,    0,   48,   46,
       45,   39,   17,   17,   17,   43,   29,   45,   29,   17,
       27,   29,   27,   40,   48,   27,   40,   43,   43,   52,
       51,   51,   27,   27,   48,   47,   47,   47,    0,   47,
       49,   43,    0,   53,    0,   49,   27,   54,   27,    0,
       55,   27,   56,   58,   59,   52,   60,   61,   27,   27,
       28,   47,   47,   47,   28,   47,   49,   28,   28,   53,
       50,   49,   62,   54,   28,   50,   55,   28,   56,   58,

       59,   50,   60,   61,   63,   64,   28,   65,   50,    0,
       28,    0,   67,   28,   28,    0,   50,   68,   62,   70,
       28,   50,    0,   28,   71,   66,    0,   50,   66,   73,
       63,   64,   74,   65,   50,   57,   75,   57,   67,    0,
       76,   57,   77,   68,   77,   70,   79,   80,   57,   72,
       71,   66,   57,   81,   66,   73,    0,   82,   74,   72,
       83,   57,   75,   57,   72,   72,   76,   57,   77,   78,
       77,   78,   79,   80,   57,   72,   84,   85,   57,   81,
       86,   88,   78,   82,   89,   72,   83,   90,   91,   92,
       72,   72,   94,   92,   93,   78,   95,   78,   96,   93,

       97,   98,   84,   85,   99,  100,   86,   88,   78,   97,
       89,  101,  102,   90,   91,   92,  103,   97,   94,   92,
       93,  104,   95,  102,   96,   93,   97,   98,  105,  108,
       99,  100,  106,  107,  109,   97,  107,  101,  102,  110,
      111,  112,  103,   97,  113,  110,  114,  104,  117,  102,
      119,  120,  106,  111,  105,  108,  122,  124,  106,  107,
      109,  125,  107,  126,  127,  110,  111,  112,  129,  130,
      113,  110,  114,  131,  117,    0,  119,  120,  106,  111,
      132,  133,  122,  124,  128,  134,  128,  125,  135,  126,
      127,  136,  138,  139,  129,  130,  141,  142,  140,  131,

      143,  128,  144,  145,  146,  148,  132,  133,  149,  150,
      128,  134,  128,  140,  135,  151,  152,  136,  138,  139,
      153,  154,  141,  142,  140,  155,  143,  128,  144,  145,
      146,  148,  156,  157,  149,  150,  158,  159,  160,  140,
      161,  151,  152,  162,  163,  164,  153,  154,  165,  166,
      167,  155,  168,  169,  170,  171,  172,  173,  156,  157,
      175,  176,  158,  159,  160,  171,  161,  177,  178,  162,
      163,  164,  179,  180,  165,  166,  167,  181,  168,  169,
      170,  171,  172,  173,  182,  183,  175,  176,  184,  186,
      187,  171,  188,  177,  178,  189,  190,  191,  179,  180,

      192,  193,  194,  181,  195,  196,  197,  198,  199,  200,
      182,  183,  201,  203,  184,  186,  187,  204,  188,  205,
      206,  189,  190,  191,  207,  208,  192,  193,  194,  209,
      195,  196,  197,  198,  199,  200,  210,  212,  201,  203,
      213,  215,  214,  204,  214,  205,  206,  216,  217,  213,
      207,  208,  218,  219,  220,  209,  221,  222,  223,  224,
      225,  222,  210,  212,  226,  227,  213,  215,  214,  228,
      214,  229,  230,  216,  217,  213,  231,  233,  218,  219,
      220,  237,  221,  222,  223,  224,  225,  222,  238,  239,
      226,  227,  241,  242,  243,  228,  244,  229,  230,  245,

      246,  247,  231,  233,  248,  249,  250,  237,  251,  254,
      255,  256,  257,  258,  238,  239,  259,  260,  241,  242,
      243,  262,  244,  263,  266,  245,  246,  247,  267,  269,
      248,  249,  250,  272,  251,  254,  255,  256,  257,  258,
      273,  274,  259,  260,  275,  276,  277,  262,  279,  263,
      266,  283,  285,  287,  267,  269,  289,  277,  290,  272,
      288,  288,  292,  293,  294,  295,  273,  274,  296,  298,
      275,  276,  277,  299,  279,  300,  301,  283,  285,  287,
      302,  303,  289,  277,  290,  304,  288,  288,  292,  293,
      294,  295,  305,  306,  296,  298,  308,  309,  310,  299,

      311,  300,  301,  314,  315,  317,  302,  303,  318,  319,
      320,  304,  321,  322,  323,  324,  326,  328,  305,  306,
      333,  335,  308,  309,  310,  337,  311,  338,  339,  314,
      315,  317,  340,  341,  318,  319,  320,  342,  321,  322,
      323,  324,  326,  328,  344,  345,  333,  335,  346,  347,
      349,  337,  350,  338,  339,  351,  352,  353,  340,  341,
      354,  355,  356,  342,  357,  358,  361,  362,  364,  366,
      344,  345,  369,  370,  346,  347,  349,  371,  350,  372,
      377,  351,  352,  353,  379,  380,  354,  355,  356,  381,
      357,  358,  361,  362,  364,  366,  384,  385,  369,  370,

      386,  387,  388,  371,  390,  372,  377,  391,  392,  393,
      379,  380,  394,  395,  396,  381,  397,  398,  399,  400,
      402,  403,  384,  385,  404,  406,  386,  387,  388,  407,
      390,  408,  410,  391,  392,  393,  412,  413,  394,  395,
      396,  414,  397,  398,  399,  400,  402,  403,  416,  418,
      404,  406,  419,  420,  422,  407,  424,  408,  410,  428,
      430,  431,  412,  413,  437,  438,  441,  414,  442,  444,
      445,  446,  448,  449,  416,  418,  450,  454,  419,  420,
      422,  456,  424,  457,  458,  428,  430,  431,  459,  464,
      437,  438,  441,  465,  442,  444,  445,  446,  448,  449,

      471,  472,  450,  454,  474,  475,  480,  456,  482,  457,
      458,  483,  486,  487,  459,  464,  490,  491,  492,  465,
      493,  497,  500,  502,  505,  506,  471,  472,  507,  509,
      474,  475,  480,  511,  482,  514,  517,  483,  486,  487,
        0,    0,  490,  491,  492,    0,  493,  497,  500,  502,
      505,  506,    0,    0,  507,  509,    0,    0,    0,  511,
        0,  514,  517,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
#include "main.h"
#include "yacc.tab.h"

#define TOKEN(name) {return SQL_##name;}
extern "C"
{
	int yywrap(void);
	int yylex(void);
}
#line 880 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 14 "lex.l"

#line 1091 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 520 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1064 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 15 "lex.l"
/* skip whitespace */;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 17 "lex.l"
TOKEN(DEALLOCATE)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 18 "lex.l"
TOKEN(PARAMETERS)
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 19 "lex.l"
TOKEN(INTERSECT)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 20 "lex.l"
TOKEN(TEMPORARY)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 21 "lex.l"
TOKEN(TIMESTAMP)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 22 "lex.l"
TOKEN(DESCRIBE)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 23 "lex.l"
TOKEN(DISTINCT)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 24 "lex.l"
TOKEN(NVARCHAR)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 25 "lex.l"
TOKEN(RESTRICT)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 26 "lex.l"
TOKEN(TRUNCATE)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 27 "lex.l"
TOKEN(ANALYZE)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 28 "lex.l"
TOKEN(BETWEEN)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 29 "lex.l"
TOKEN(CASCADE)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 30 "lex.l"
TOKEN(COLUMNS)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 31 "lex.l"
TOKEN(CONTROL)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 32 "lex.l"
TOKEN(DEFAULT)
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 33 "lex.l"
TOKEN(EXECUTE)
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 34 "lex.l"
TOKEN(EXPLAIN)
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 35 "lex.l"
TOKEN(INTEGER)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 36 "lex.l"
TOKEN(NATURAL)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 37 "lex.l"
TOKEN(PREPARE)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 38 "lex.l"
TOKEN(PRIMARY)
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 39 "lex.l"
TOKEN(SCHEMAS)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 40 "lex.l"
TOKEN(SPATIAL)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 41 "lex.l"
TOKEN(VARCHAR)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 42 "lex.l"
TOKEN(VIRTUAL)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 43 "lex.l"
TOKEN(BEFORE)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 44 "lex.l"
TOKEN(COLUMN)
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 45 "lex.l"
TOKEN(CREATE)
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 46 "lex.l"
TOKEN(DELETE)
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 47 "lex.l"
TOKEN(DIRECT)
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 48 "lex.l"
TOKEN(DOUBLE)
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 49 "lex.l"
TOKEN(ESCAPE)
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 50 "lex.l"
TOKEN(EXCEPT)
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 51 "lex.l"
TOKEN(EXISTS)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 52 "lex.l"
TOKEN(EXTRACT)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 53 "lex.l"
TOKEN(CAST)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 54 "lex.l"
TOKEN(FORMAT)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 55 "lex.l"
TOKEN(GLOBAL)
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 56 "lex.l"
TOKEN(HAVING)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 57 "lex.l"
TOKEN(IMPORT)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 58 "lex.l"
TOKEN(INSERT)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 59 "lex.l"
TOKEN(ISNULL)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 60 "lex.l"
TOKEN(OFFSET)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 61 "lex.l"
TOKEN(RENAME)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 62 "lex.l"
TOKEN(SCHEMA)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "lex.l"
TOKEN(SELECT)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "lex.l"
TOKEN(SORTED)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 65 "lex.l"
TOKEN(TABLES)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 66 "lex.l"
TOKEN(UNIQUE)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 67 "lex.l"
TOKEN(UNLOAD)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 68 "lex.l"
TOKEN(UPDATE)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 69 "lex.l"
TOKEN(VALUES)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 70 "lex.l"
TOKEN(AFTER)
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 71 "lex.l"
TOKEN(ALTER)
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 72 "lex.l"
TOKEN(ARRAY)
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 73 "lex.l"
TOKEN(CROSS)
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 74 "lex.l"
TOKEN(DELTA)
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 75 "lex.l"
TOKEN(FLOAT)
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 76 "lex.l"
TOKEN(GROUP)
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 77 "lex.l"
TOKEN(INDEX)
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 78 "lex.l"
TOKEN(INNER)
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 79 "lex.l"
TOKEN(LIMIT)
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 80 "lex.l"
TOKEN(LOCAL)
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 81 "lex.l"
TOKEN(MERGE)
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 82 "lex.l"
TOKEN(MINUS)
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 83 "lex.l"
TOKEN(ORDER)
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 84 "lex.l"
TOKEN(OUTER)
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 85 "lex.l"
TOKEN(RIGHT)
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 86 "lex.l"
TOKEN(TABLE)
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 87 "lex.l"
TOKEN(UNION)
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 88 "lex.l"
TOKEN(USING)
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 89 "lex.l"
TOKEN(WHERE)
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 90 "lex.l"
TOKEN(CALL)
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 91 "lex.l"
TOKEN(CASE)
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 92 "lex.l"
TOKEN(CHAR)
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 93 "lex.l"
TOKEN(COPY)
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 94 "lex.l"
TOKEN(DATE)
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 95 "lex.l"
TOKEN(DATETIME)
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 96 "lex.l"
TOKEN(DESC)
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 97 "lex.l"
TOKEN(DROP)
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 98 "lex.l"
TOKEN(ELSE)
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 99 "lex.l"
TOKEN(FILE)
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 100 "lex.l"
TOKEN(FROM)
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 101 "lex.l"
TOKEN(FULL)
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 102 "lex.l"
TOKEN(HASH)
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 103 "lex.l"
TOKEN(HINT)
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 104 "lex.l"
TOKEN(INTO)
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 105 "lex.l"
TOKEN(JOIN)
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 106 "lex.l"
TOKEN(LEFT)
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 107 "lex.l"
TOKEN(LIKE)
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 108 "lex.l"
TOKEN(ILIKE)
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 109 "lex.l"
TOKEN(LOAD)
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 110 "lex.l"
TOKEN(LONG)
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 111 "lex.l"
TOKEN(NULL)
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 112 "lex.l"
TOKEN(PLAN)
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 113 "lex.l"
TOKEN(SHOW)
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 114 "lex.l"
TOKEN(TEXT)
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 115 "lex.l"
TOKEN(THEN)
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 116 "lex.l"
TOKEN(TIME)
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 117 "lex.l"
TOKEN(VIEW)
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 118 "lex.l"
TOKEN(WHEN)
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 119 "lex.l"
TOKEN(WITH)
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 120 "lex.l"
TOKEN(ADD)
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 121 "lex.l"
TOKEN(ALL)
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 122 "lex.l"
TOKEN(AND)
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 123 "lex.l"
TOKEN(ASC)
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 124 "lex.l"
TOKEN(END)
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 125 "lex.l"
TOKEN(FOR)
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 126 "lex.l"
TOKEN(INT)
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 127 "lex.l"
TOKEN(KEY)
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 128 "lex.l"
TOKEN(NOT)
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 129 "lex.l"
TOKEN(OFF)
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 130 "lex.l"
TOKEN(SET)
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 131 "lex.l"
TOKEN(TOP)
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 132 "lex.l"
TOKEN(AS)
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 133 "lex.l"
TOKEN(BY)
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 134 "lex.l"
TOKEN(IF)
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 135 "lex.l"
TOKEN(IN)
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 136 "lex.l"
TOKEN(IS)
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 137 "lex.l"
TOKEN(OF)
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 138 "lex.l"
TOKEN(ON)
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 139 "lex.l"
TOKEN(OR)
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 140 "lex.l"
TOKEN(TO)
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 141 "lex.l"
TOKEN(SECOND)
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 142 "lex.l"
TOKEN(MINUTE)
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 143 "lex.l"
TOKEN(HOUR)
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 144 "lex.l"
TOKEN(DAY)
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 145 "lex.l"
TOKEN(MONTH)
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 146 "lex.l"
TOKEN(YEAR)
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 147 "lex.l"
TOKEN(TRUE)
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 148 "lex.l"
TOKEN(FALSE)
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 149 "lex.l"
TOKEN(TRANSACTION)
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 150 "lex.l"
TOKEN(BEGIN)
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 151 "lex.l"
TOKEN(ROLLBACK)
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 152 "lex.l"
TOKEN(COMMIT)
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 154 "lex.l"
{
	yylval.sval = yytext;
	return SQL_IDENTIFIER;
}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 158 "lex.l"
{
    yylval.ival = atol(yytext);
	    return SQL_INTVAL;
		}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 163 "lex.l"
{ 
	yylval.fval = atof(yytext);
	return SQL_FLOATVAL;
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 168 "lex.l"
{ return yytext[0]; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 170 "lex.l"
ECHO;
	YY_BREAK
#line 1868 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 520 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 520 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 519);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 170 "lex.l"


int yywrap(void)
{
	puts("--------the file is end");
	return 1;
}

