
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 148
#define YY_END_OF_BUFFER 149
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[531] =
    {   0,
        0,    0,  149,  148,    1,  148,  147,  147,  145,  147,
      147,  147,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  147,    1,  139,  145,
      146,  141,  140,  138,  142,  144,  144,  144,  144,  144,
      144,  117,  144,  118,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  119,  144,
      144,  120,  121,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  122,  123,  124,  144,  144,

      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  125,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  143,  146,  105,  144,  106,  144,
      144,  107,  144,  108,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  129,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  109,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  110,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  111,  144,  144,  112,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  113,  144,  144,  114,  144,

      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  115,  144,  144,  144,  144,  144,  144,  144,
      144,  116,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,   75,  144,   76,   38,   77,  144,  144,  144,
       78,  144,  144,   79,  144,  144,  144,  144,   81,  144,
      144,  144,   82,   83,  144,  144,  144,  144,  144,  144,
      144,   84,  144,  144,   85,   86,  144,  144,   87,  144,
       88,  128,  144,  144,  144,  144,  144,  144,   89,  144,
       90,   91,   92,  144,   94,  144,   95,  144,  144,  144,

      144,   96,  144,  144,  144,  144,  144,   97,  144,  144,
      144,  144,  144,  144,  144,  144,  144,   98,  144,  144,
      144,  144,   99,  100,  101,  144,  132,  144,  144,  144,
      144,  144,  144,  144,  144,  102,  144,  103,  144,  104,
      131,   55,   56,  144,   57,  144,  135,  144,  144,  144,
      144,  144,  144,   58,  144,  144,  144,  144,   59,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  133,
       60,  144,  144,   61,  144,   93,  144,   62,   63,  144,
      144,  144,  144,   64,   65,   66,   67,  144,  130,  144,
      144,  144,   68,   69,  144,  144,  144,  144,  144,   70,

      144,  144,  144,  144,  144,  144,   71,  144,  144,  144,
      144,   72,  144,  144,  144,   73,  144,  144,  144,   74,
      144,   28,  144,  144,   29,  137,  144,   30,  144,  144,
      144,   31,  144,   32,  144,   33,   34,   35,  144,   36,
      144,  144,   39,   40,   41,   42,   43,  144,  144,   44,
      127,  144,  144,   45,  144,  144,  144,   46,  144,  144,
       47,  126,   48,   49,  144,   50,  144,  144,  144,  144,
       51,   52,   53,   54,  144,  144,   12,   13,   14,   15,
       16,  144,  144,   17,  144,  144,   18,   19,   37,   20,
      144,   21,  144,  144,   22,   23,  144,  144,   24,   25,

      144,  144,  144,  144,   26,   27,   80,  144,    7,    8,
      144,    9,  144,   10,  136,  144,  144,  144,   11,  144,
        4,  144,    5,    6,  144,    2,    3,  144,  134,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    1,    1,    1,    4,    1,    1,    4,
        4,    4,    4,    4,    5,    6,    4,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    4,    4,    8,
        9,   10,    4,    1,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
        4,    1,    4,    4,    1,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,    4,   63,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1
    } ;

static yyconst flex_int16_t yy_base[532] =
    {   0,
        0,    0,  145, 1071,  139,  130, 1071,  131,   58,   57,
      128,  127,   54,   54,   62,  106,   50,  150,   49,   82,
      192,   60,   71,   99,  107,  131,  143,  142,    0,  158,
      235,  277,  194,  109,  147,  108,   72,  128, 1071,   85,
       81, 1071, 1071, 1071, 1071,    0,  115,  146,  183,  214,
      152,  171,  213,    0,  190,  200,  241,  211,  238,  287,
      204,  226,  246,  246,  264,  267,  330,  259,  260,  259,
      257,  275,  290,  288,  290,  304,  296,  294,    0,  308,
      306,  343,  313,  321,  309,  332,  329,  366,  326,  331,
      337,  335,  338,  362,  374,  372,    0,  375,  362,  367,

      385,  382,  378,  383,  382,  388,  395,  384,  384,  402,
      407,  397,  409,  406,  410,  429,  422,  423,  423,  425,
      433,  434,  422,  443, 1071,   74,    0,  441,    0,  443,
      437,    0,  453,    0,  440,  450,  438,  450,  479,  448,
      446,  458,  458,  454,  482,  467,  484,    0,  478,  490,
      491,  491,  490,  478,  498,  485,  497,    0,  502,  501,
      504,  494,  502,  500,  500,  518,  529,  518,  521,  523,
      534,  517,  533,  533,  523,  528,  536,  533,  545,  546,
      547,  548,  533,  541,    0,  538,  554,  556,  562,  569,
      564,  568,  561,  563,  565,    0,  575,  570,  571,  588,

      589,  594,  584,  583,  587,  601,  583,  596,  593,  601,
      592,  605,    0,  588,  595,  597,  606,  606,  603,  613,
      629,    0,  621,  633,  625,  624,  644,  632,  629,  648,
      629,  634,  641,  648,  639,  640,  644,  638,  642,  651,
      656,  669,    0,  674,    0,    0,    0,  666,  677,  669,
        0,  670,  672,  672,  682,  676,  678,  698,  684,  700,
      695,  694,    0,    0,  691,  692,  688,  690,  710,  713,
      710,    0,  699,  720,    0,    0,  721,  710,    0,  713,
        0,    0,  726,  720,  715,  724,  725,  737,    0,  734,
        0,    0,    0,  729,    0,  738,    0,  746,  739,  746,

      738,    0,  757,  756,  744,  745,  753,    0,  766,  770,
      760,  756,  758,  777,  770,  776,  788,    0,  789,  786,
      791,  783,    0,    0,  782,  783,    0,  800,  792,  786,
      807,  790,  804,  807,  805,    0,  793,    0,  810,    0,
        0,    0,    0,  792,    0,  814,    0,  818,  821,  812,
      810,  816,  830,    0,  833,  828,  834,  842,    0,  839,
      830,  839,  849,  850,  838,  839,  841,  853,  860,    0,
        0,  844,  853,    0,  859,    0,  847,    0,    0,  850,
      866,  856,  865,    0,    0,    0,    0,  873,    0,  881,
      875,  867,    0,    0,  889,  877,  880,  894,  891,    0,

      901,  904,  902,  887,  906,  910,  893,  896,  895,  915,
      916,    0,  913,  915,  917,    0,  904,  926,  928,    0,
      925,    0,  920,  930,  920,    0,  934,    0,  934,  947,
      931,    0,  950,    0,  951,    0,    0,    0,  952,    0,
      944,  939,    0,    0,    0,    0,    0,  944,  958,    0,
        0,  952,  965,    0,  947,  963,  944,    0,  967,  968,
      955,    0,    0,    0,  963,    0,  978,  980,  979,  966,
        0,    0,    0,    0,  969,  979,    0,    0,    0,    0,
        0,  993,  998,    0,  997,  983,    0,    0,    0,    0,
     1001,    0,  988, 1004,    0,    0,  990, 1000,    0,    0,

      996, 1002,  996, 1013,    0,    0,    0,  999,    0,    0,
     1000,    0, 1003,    0,    0,  997, 1007, 1017,    0, 1022,
        0, 1012,    0,    0, 1018,    0,    0, 1020,    0, 1071,
       73
    } ;

static yyconst flex_int16_t yy_def[532] =
    {   0,
      530,    1,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  530,  530,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,

      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,    0,
      530
    } ;

static yyconst flex_int16_t yy_nxt[1135] =
    {   0,
        4,    5,    6,    7,    8,    7,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   29,   36,   29,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   29,
       36,   29,   37,   41,   40,   42,   43,   47,   53,   48,
       74,   64,   55,   65,   46,   49,   75,   50,   66,   56,
      126,   51,   52,   67,   84,   85,   57,  126,   54,   58,
       41,   40,   76,   47,   53,   48,   74,   64,   55,   65,

       77,   49,   75,   50,   66,   56,   78,   51,   52,   67,
       84,   85,   57,   86,   54,   58,   59,   87,   76,  120,
       60,   89,  124,   88,   61,   90,   77,  121,  127,   38,
       62,   91,   78,   63,  125,   45,   44,   40,   39,   86,
       38,   92,   59,   87,  530,  120,   60,   89,  124,   88,
       61,   90,  100,  121,  127,   93,   62,   91,   96,   63,
       68,   94,   95,  101,  122,  123,   97,   92,   69,  102,
       98,   70,  103,   99,   71,  128,  104,   72,  100,  133,
       73,   93,  105,  134,   96,  530,   68,   94,   95,  101,
      122,  123,   97,  530,   69,  102,   98,   70,  103,   99,

       71,  128,  104,   72,  129,  133,   73,   79,  105,  134,
      140,  138,  130,   80,   81,   82,  530,  117,  139,  118,
       83,  530,  119,  530,  131,  145,  530,  132,  135,  136,
      129,  153,  154,   79,  530,  146,  140,  138,  130,   80,
       81,   82,  137,  117,  139,  118,   83,  106,  119,  107,
      131,  145,  108,  132,  135,  136,  155,  153,  154,  109,
      110,  146,  141,  142,  143,  530,  144,  147,  137,  530,
      156,  530,  148,  106,  157,  107,  530,  158,  108,  159,
      165,  166,  155,  167,  168,  109,  110,  111,  141,  142,
      143,  112,  144,  147,  113,  114,  156,  149,  148,  169,

      157,  115,  150,  158,  116,  159,  165,  166,  151,  167,
      168,  170,  171,  111,  172,  152,  530,  112,  530,  175,
      113,  114,  530,  149,  176,  169,  177,  115,  150,  530,
      116,  178,  173,  530,  151,  174,  183,  170,  171,  184,
      172,  152,  160,  185,  161,  175,  530,  186,  162,  187,
      176,  188,  177,  192,  193,  163,  179,  178,  173,  164,
      194,  174,  183,  530,  195,  184,  180,  196,  160,  185,
      161,  181,  182,  186,  162,  187,  189,  188,  190,  192,
      193,  163,  179,  197,  198,  164,  194,  199,  200,  191,
      195,  201,  180,  196,  202,  203,  204,  181,  182,  208,

      205,  206,  189,  209,  190,  210,  207,  211,  214,  197,
      198,  215,  216,  199,  200,  191,  212,  201,  217,  218,
      202,  203,  204,  220,  213,  208,  205,  206,  221,  209,
      219,  210,  207,  211,  214,  222,  227,  215,  216,  223,
      225,  228,  212,  226,  217,  218,  229,  231,  233,  220,
      213,  234,  230,  235,  221,  236,  219,  237,  238,  224,
      232,  222,  227,  239,  240,  223,  225,  228,  241,  226,
      242,  243,  229,  231,  233,  247,  248,  234,  230,  235,
      249,  236,  530,  237,  238,  224,  232,  250,  251,  239,
      240,  244,  252,  245,  241,  253,  242,  243,  254,  255,

      256,  247,  248,  259,  260,  257,  249,  261,  246,  262,
      263,  264,  265,  250,  251,  266,  267,  244,  252,  245,
      258,  253,  268,  269,  254,  255,  256,  270,  271,  259,
      260,  257,  272,  261,  246,  262,  263,  264,  265,  273,
      274,  266,  267,  275,  276,  277,  258,  278,  268,  269,
      279,  280,  281,  270,  271,  282,  283,  284,  272,  285,
      286,  287,  288,  290,  291,  273,  274,  292,  293,  275,
      276,  277,  289,  278,  294,  295,  279,  280,  281,  296,
      297,  282,  283,  284,  298,  285,  286,  287,  288,  290,
      291,  299,  300,  292,  293,  301,  302,  303,  289,  304,

      294,  295,  305,  306,  307,  296,  297,  308,  309,  310,
      298,  311,  312,  313,  314,  315,  316,  299,  300,  317,
      318,  301,  302,  303,  319,  304,  320,  321,  305,  306,
      307,  322,  323,  308,  309,  310,  324,  311,  312,  313,
      314,  315,  316,  325,  326,  317,  318,  327,  331,  329,
      319,  330,  320,  321,  332,  333,  328,  322,  323,  334,
      335,  336,  324,  337,  338,  340,  341,  342,  339,  325,
      326,  343,  344,  327,  331,  329,  345,  330,  346,  347,
      332,  333,  328,  348,  349,  334,  335,  336,  350,  337,
      338,  340,  341,  342,  339,  351,  352,  343,  344,  353,

      354,  355,  345,  356,  346,  347,  357,  358,  359,  348,
      349,  360,  361,  362,  350,  363,  364,  365,  366,  367,
      368,  351,  352,  369,  370,  353,  354,  355,  371,  356,
      372,  373,  357,  358,  359,  374,  375,  360,  361,  362,
      376,  363,  364,  365,  366,  367,  368,  377,  378,  369,
      370,  379,  380,  381,  371,  383,  372,  373,  384,  385,
      386,  374,  375,  389,  382,  390,  376,  387,  388,  391,
      392,  393,  394,  377,  378,  395,  396,  379,  380,  381,
      397,  383,  398,  399,  384,  385,  386,  400,  401,  389,
      382,  390,  402,  387,  388,  391,  392,  393,  394,  403,

      404,  395,  396,  405,  406,  407,  397,  408,  398,  399,
      409,  410,  411,  400,  401,  412,  413,  414,  402,  415,
      416,  417,  418,  419,  420,  403,  404,  421,  422,  405,
      406,  407,  423,  408,  424,  425,  409,  410,  411,  426,
      427,  412,  413,  414,  428,  415,  416,  417,  418,  419,
      420,  429,  430,  421,  422,  431,  432,  433,  423,  434,
      424,  425,  435,  436,  437,  426,  427,  438,  439,  440,
      428,  441,  442,  443,  444,  445,  446,  429,  430,  447,
      448,  431,  432,  433,  449,  434,  450,  451,  435,  436,
      437,  452,  453,  438,  439,  440,  454,  441,  442,  443,

      444,  445,  446,  455,  456,  447,  448,  457,  458,  459,
      449,  460,  450,  451,  461,  462,  463,  452,  453,  464,
      465,  466,  454,  467,  468,  469,  470,  471,  472,  455,
      456,  473,  474,  457,  458,  459,  475,  460,  476,  477,
      461,  462,  463,  478,  479,  464,  465,  466,  480,  467,
      468,  469,  470,  471,  472,  481,  482,  473,  474,  483,
      484,  485,  475,  486,  476,  477,  487,  488,  489,  478,
      479,  490,  491,  492,  480,  493,  494,  495,  496,  497,
      498,  481,  482,  499,  500,  483,  484,  485,  501,  486,
      502,  503,  487,  488,  489,  504,  505,  490,  491,  492,

      506,  493,  494,  495,  496,  497,  498,  507,  508,  499,
      500,  509,  510,  511,  501,  512,  502,  503,  513,  514,
      515,  504,  505,  516,  517,  518,  506,  519,  520,  521,
      522,  523,  524,  507,  508,  525,  526,  509,  510,  511,
      527,  512,  528,  529,  513,  514,  515,  530,  530,  516,
      517,  518,  530,  519,  520,  521,  522,  523,  524,  530,
      530,  525,  526,  530,  530,  530,  527,  530,  528,  529,
        3,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,

      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530
    } ;

static yyconst flex_int16_t yy_chk[1135] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    9,    9,   10,   10,   13,   14,   13,
       19,   17,   15,   17,  531,   13,   19,   13,   17,   15,
      126,   13,   13,   17,   22,   23,   15,   41,   14,   15,
       40,   40,   20,   13,   14,   13,   19,   17,   15,   17,

       20,   13,   19,   13,   17,   15,   20,   13,   13,   17,
       22,   23,   15,   24,   14,   15,   16,   24,   20,   34,
       16,   25,   36,   24,   16,   25,   20,   34,   47,   38,
       16,   25,   20,   16,   37,   12,   11,    8,    6,   24,
        5,   26,   16,   24,    3,   34,   16,   25,   36,   24,
       16,   25,   28,   34,   47,   26,   16,   25,   27,   16,
       18,   26,   26,   28,   35,   35,   27,   26,   18,   28,
       27,   18,   30,   27,   18,   48,   30,   18,   28,   51,
       18,   26,   30,   52,   27,    0,   18,   26,   26,   28,
       35,   35,   27,    0,   18,   28,   27,   18,   30,   27,

       18,   48,   30,   18,   49,   51,   18,   21,   30,   52,
       56,   55,   49,   21,   21,   21,    0,   33,   55,   33,
       21,    0,   33,    0,   50,   58,    0,   50,   53,   53,
       49,   61,   61,   21,    0,   58,   56,   55,   49,   21,
       21,   21,   53,   33,   55,   33,   21,   31,   33,   31,
       50,   58,   31,   50,   53,   53,   62,   61,   61,   31,
       31,   58,   57,   57,   57,    0,   57,   59,   53,    0,
       63,    0,   59,   31,   64,   31,    0,   65,   31,   66,
       68,   69,   62,   70,   71,   31,   31,   32,   57,   57,
       57,   32,   57,   59,   32,   32,   63,   60,   59,   72,

       64,   32,   60,   65,   32,   66,   68,   69,   60,   70,
       71,   73,   74,   32,   75,   60,    0,   32,    0,   77,
       32,   32,    0,   60,   78,   72,   80,   32,   60,    0,
       32,   81,   76,    0,   60,   76,   83,   73,   74,   84,
       75,   60,   67,   85,   67,   77,    0,   86,   67,   87,
       78,   87,   80,   89,   90,   67,   82,   81,   76,   67,
       91,   76,   83,    0,   92,   84,   82,   93,   67,   85,
       67,   82,   82,   86,   67,   87,   88,   87,   88,   89,
       90,   67,   82,   94,   95,   67,   91,   96,   98,   88,
       92,   99,   82,   93,  100,  101,  102,   82,   82,  104,

      102,  103,   88,  105,   88,  106,  103,  107,  108,   94,
       95,  109,  110,   96,   98,   88,  107,   99,  111,  112,
      100,  101,  102,  113,  107,  104,  102,  103,  114,  105,
      112,  106,  103,  107,  108,  115,  118,  109,  110,  116,
      117,  119,  107,  117,  111,  112,  120,  121,  122,  113,
      107,  123,  120,  124,  114,  128,  112,  130,  131,  116,
      121,  115,  118,  133,  135,  116,  117,  119,  136,  117,
      137,  138,  120,  121,  122,  140,  141,  123,  120,  124,
      142,  128,    0,  130,  131,  116,  121,  143,  144,  133,
      135,  139,  145,  139,  136,  146,  137,  138,  147,  149,

      150,  140,  141,  152,  153,  151,  142,  154,  139,  155,
      156,  157,  159,  143,  144,  160,  161,  139,  145,  139,
      151,  146,  162,  163,  147,  149,  150,  164,  165,  152,
      153,  151,  166,  154,  139,  155,  156,  157,  159,  167,
      168,  160,  161,  169,  170,  171,  151,  172,  162,  163,
      173,  174,  175,  164,  165,  176,  177,  178,  166,  179,
      180,  181,  182,  183,  184,  167,  168,  186,  187,  169,
      170,  171,  182,  172,  188,  189,  173,  174,  175,  190,
      191,  176,  177,  178,  192,  179,  180,  181,  182,  183,
      184,  193,  194,  186,  187,  195,  197,  198,  182,  199,

      188,  189,  200,  201,  202,  190,  191,  203,  204,  205,
      192,  206,  207,  208,  209,  210,  211,  193,  194,  212,
      214,  195,  197,  198,  215,  199,  216,  217,  200,  201,
      202,  218,  219,  203,  204,  205,  220,  206,  207,  208,
      209,  210,  211,  221,  223,  212,  214,  224,  226,  225,
      215,  225,  216,  217,  227,  228,  224,  218,  219,  229,
      230,  231,  220,  232,  233,  234,  235,  236,  233,  221,
      223,  237,  238,  224,  226,  225,  239,  225,  240,  241,
      227,  228,  224,  242,  244,  229,  230,  231,  248,  232,
      233,  234,  235,  236,  233,  249,  250,  237,  238,  252,

      253,  254,  239,  255,  240,  241,  256,  257,  258,  242,
      244,  259,  260,  261,  248,  262,  265,  266,  267,  268,
      269,  249,  250,  270,  271,  252,  253,  254,  273,  255,
      274,  277,  256,  257,  258,  278,  280,  259,  260,  261,
      283,  262,  265,  266,  267,  268,  269,  284,  285,  270,
      271,  286,  287,  288,  273,  290,  274,  277,  294,  296,
      298,  278,  280,  300,  288,  301,  283,  299,  299,  303,
      304,  305,  306,  284,  285,  307,  309,  286,  287,  288,
      310,  290,  311,  312,  294,  296,  298,  313,  314,  300,
      288,  301,  315,  299,  299,  303,  304,  305,  306,  316,

      317,  307,  309,  319,  320,  321,  310,  322,  311,  312,
      325,  326,  328,  313,  314,  329,  330,  331,  315,  332,
      333,  334,  335,  337,  339,  316,  317,  344,  346,  319,
      320,  321,  348,  322,  349,  350,  325,  326,  328,  351,
      352,  329,  330,  331,  353,  332,  333,  334,  335,  337,
      339,  355,  356,  344,  346,  357,  358,  360,  348,  361,
      349,  350,  362,  363,  364,  351,  352,  365,  366,  367,
      353,  368,  369,  372,  373,  375,  377,  355,  356,  380,
      381,  357,  358,  360,  382,  361,  383,  388,  362,  363,
      364,  390,  391,  365,  366,  367,  392,  368,  369,  372,

      373,  375,  377,  395,  396,  380,  381,  397,  398,  399,
      382,  401,  383,  388,  402,  403,  404,  390,  391,  405,
      406,  407,  392,  408,  409,  410,  411,  413,  414,  395,
      396,  415,  417,  397,  398,  399,  418,  401,  419,  421,
      402,  403,  404,  423,  424,  405,  406,  407,  425,  408,
      409,  410,  411,  413,  414,  427,  429,  415,  417,  430,
      431,  433,  418,  435,  419,  421,  439,  441,  442,  423,
      424,  448,  449,  452,  425,  453,  455,  456,  457,  459,
      460,  427,  429,  461,  465,  430,  431,  433,  467,  435,
      468,  469,  439,  441,  442,  470,  475,  448,  449,  452,

      476,  453,  455,  456,  457,  459,  460,  482,  483,  461,
      465,  485,  486,  491,  467,  493,  468,  469,  494,  497,
      498,  470,  475,  501,  502,  503,  476,  504,  508,  511,
      513,  516,  517,  482,  483,  518,  520,  485,  486,  491,
      522,  493,  525,  528,  494,  497,  498,    0,    0,  501,
      502,  503,    0,  504,  508,  511,  513,  516,  517,    0,
        0,  518,  520,    0,    0,    0,  522,    0,  525,  528,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,

      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
#include "main.h"
#include "yacc.tab.h"

#define TOKEN(name) {return SQL_##name;}
extern "C"
{
	int yywrap(void);
	int yylex(void);
}
#line 888 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 14 "lex.l"

#line 1099 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 531 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1071 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 15 "lex.l"
/* skip whitespace */;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 17 "lex.l"
TOKEN(DEALLOCATE)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 18 "lex.l"
TOKEN(PARAMETERS)
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 19 "lex.l"
TOKEN(INTERSECT)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 20 "lex.l"
TOKEN(TEMPORARY)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 21 "lex.l"
TOKEN(TIMESTAMP)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 22 "lex.l"
TOKEN(DESCRIBE)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 23 "lex.l"
TOKEN(DISTINCT)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 24 "lex.l"
TOKEN(NVARCHAR)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 25 "lex.l"
TOKEN(RESTRICT)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 26 "lex.l"
TOKEN(TRUNCATE)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 27 "lex.l"
TOKEN(ANALYZE)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 28 "lex.l"
TOKEN(BETWEEN)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 29 "lex.l"
TOKEN(CASCADE)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 30 "lex.l"
TOKEN(COLUMNS)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 31 "lex.l"
TOKEN(CONTROL)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 32 "lex.l"
TOKEN(DEFAULT)
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 33 "lex.l"
TOKEN(EXECUTE)
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 34 "lex.l"
TOKEN(EXPLAIN)
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 35 "lex.l"
TOKEN(INTEGER)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 36 "lex.l"
TOKEN(NATURAL)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 37 "lex.l"
TOKEN(PREPARE)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 38 "lex.l"
TOKEN(PRIMARY)
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 39 "lex.l"
TOKEN(SCHEMAS)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 40 "lex.l"
TOKEN(SPATIAL)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 41 "lex.l"
TOKEN(VARCHAR)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 42 "lex.l"
TOKEN(VIRTUAL)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 43 "lex.l"
TOKEN(BEFORE)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 44 "lex.l"
TOKEN(COLUMN)
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 45 "lex.l"
TOKEN(CREATE)
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 46 "lex.l"
TOKEN(DELETE)
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 47 "lex.l"
TOKEN(DIRECT)
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 48 "lex.l"
TOKEN(DOUBLE)
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 49 "lex.l"
TOKEN(ESCAPE)
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 50 "lex.l"
TOKEN(EXCEPT)
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 51 "lex.l"
TOKEN(EXISTS)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 52 "lex.l"
TOKEN(EXTRACT)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 53 "lex.l"
TOKEN(CAST)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 54 "lex.l"
TOKEN(FORMAT)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 55 "lex.l"
TOKEN(GLOBAL)
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 56 "lex.l"
TOKEN(HAVING)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 57 "lex.l"
TOKEN(IMPORT)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 58 "lex.l"
TOKEN(INSERT)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 59 "lex.l"
TOKEN(ISNULL)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 60 "lex.l"
TOKEN(OFFSET)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 61 "lex.l"
TOKEN(RENAME)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 62 "lex.l"
TOKEN(SCHEMA)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "lex.l"
TOKEN(SELECT)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "lex.l"
TOKEN(SORTED)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 65 "lex.l"
TOKEN(TABLES)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 66 "lex.l"
TOKEN(UNIQUE)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 67 "lex.l"
TOKEN(UNLOAD)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 68 "lex.l"
TOKEN(UPDATE)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 69 "lex.l"
TOKEN(VALUES)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 70 "lex.l"
TOKEN(AFTER)
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 71 "lex.l"
TOKEN(ALTER)
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 72 "lex.l"
TOKEN(ARRAY)
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 73 "lex.l"
TOKEN(CROSS)
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 74 "lex.l"
TOKEN(DELTA)
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 75 "lex.l"
TOKEN(FLOAT)
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 76 "lex.l"
TOKEN(GROUP)
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 77 "lex.l"
TOKEN(INDEX)
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 78 "lex.l"
TOKEN(INNER)
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 79 "lex.l"
TOKEN(LIMIT)
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 80 "lex.l"
TOKEN(LOCAL)
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 81 "lex.l"
TOKEN(MERGE)
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 82 "lex.l"
TOKEN(MINUS)
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 83 "lex.l"
TOKEN(ORDER)
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 84 "lex.l"
TOKEN(OUTER)
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 85 "lex.l"
TOKEN(RIGHT)
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 86 "lex.l"
TOKEN(TABLE)
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 87 "lex.l"
TOKEN(UNION)
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 88 "lex.l"
TOKEN(USING)
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 89 "lex.l"
TOKEN(WHERE)
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 90 "lex.l"
TOKEN(CALL)
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 91 "lex.l"
TOKEN(CASE)
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 92 "lex.l"
TOKEN(CHAR)
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 93 "lex.l"
TOKEN(COPY)
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 94 "lex.l"
TOKEN(DATE)
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 95 "lex.l"
TOKEN(DATETIME)
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 96 "lex.l"
TOKEN(DESC)
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 97 "lex.l"
TOKEN(DROP)
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 98 "lex.l"
TOKEN(ELSE)
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 99 "lex.l"
TOKEN(FILE)
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 100 "lex.l"
TOKEN(FROM)
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 101 "lex.l"
TOKEN(FULL)
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 102 "lex.l"
TOKEN(HASH)
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 103 "lex.l"
TOKEN(HINT)
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 104 "lex.l"
TOKEN(INTO)
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 105 "lex.l"
TOKEN(JOIN)
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 106 "lex.l"
TOKEN(LEFT)
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 107 "lex.l"
TOKEN(LIKE)
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 108 "lex.l"
TOKEN(ILIKE)
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 109 "lex.l"
TOKEN(LOAD)
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 110 "lex.l"
TOKEN(LONG)
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 111 "lex.l"
TOKEN(NULL)
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 112 "lex.l"
TOKEN(PLAN)
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 113 "lex.l"
TOKEN(SHOW)
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 114 "lex.l"
TOKEN(TEXT)
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 115 "lex.l"
TOKEN(THEN)
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 116 "lex.l"
TOKEN(TIME)
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 117 "lex.l"
TOKEN(VIEW)
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 118 "lex.l"
TOKEN(WHEN)
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 119 "lex.l"
TOKEN(WITH)
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 120 "lex.l"
TOKEN(ADD)
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 121 "lex.l"
TOKEN(ALL)
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 122 "lex.l"
TOKEN(AND)
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 123 "lex.l"
TOKEN(ASC)
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 124 "lex.l"
TOKEN(END)
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 125 "lex.l"
TOKEN(FOR)
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 126 "lex.l"
TOKEN(INT)
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 127 "lex.l"
TOKEN(KEY)
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 128 "lex.l"
TOKEN(NOT)
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 129 "lex.l"
TOKEN(OFF)
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 130 "lex.l"
TOKEN(SET)
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 131 "lex.l"
TOKEN(TOP)
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 132 "lex.l"
TOKEN(AS)
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 133 "lex.l"
TOKEN(BY)
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 134 "lex.l"
TOKEN(IF)
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 135 "lex.l"
TOKEN(IN)
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 136 "lex.l"
TOKEN(IS)
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 137 "lex.l"
TOKEN(OF)
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 138 "lex.l"
TOKEN(ON)
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 139 "lex.l"
TOKEN(OR)
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 140 "lex.l"
TOKEN(TO)
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 141 "lex.l"
TOKEN(SECOND)
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 142 "lex.l"
TOKEN(MINUTE)
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 143 "lex.l"
TOKEN(HOUR)
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 144 "lex.l"
TOKEN(DAY)
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 145 "lex.l"
TOKEN(MONTH)
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 146 "lex.l"
TOKEN(YEAR)
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 147 "lex.l"
TOKEN(TRUE)
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 148 "lex.l"
TOKEN(FALSE)
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 149 "lex.l"
TOKEN(TRANSACTION)
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 150 "lex.l"
TOKEN(BEGIN)
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 151 "lex.l"
TOKEN(ROLLBACK)
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 152 "lex.l"
TOKEN(COMMIT)
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 154 "lex.l"
TOKEN(EQUALS)
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 155 "lex.l"
TOKEN(NOTEQUALS)
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 156 "lex.l"
TOKEN(NOTEQUALS)
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 157 "lex.l"
TOKEN(LESSEQ)
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 158 "lex.l"
TOKEN(GREATEREQ)
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 159 "lex.l"
TOKEN(CONCAT)
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 161 "lex.l"
{
	yylval.sval = yytext;
	return SQL_IDENTIFIER;
}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 165 "lex.l"
{
    yylval.ival = atol(yytext);
	    return SQL_INTVAL;
		}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 170 "lex.l"
{ 
	yylval.fval = atof(yytext);
	return SQL_FLOATVAL;
}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 175 "lex.l"
{ return yytext[0]; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 177 "lex.l"
ECHO;
	YY_BREAK
#line 1906 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 531 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 531 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 530);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 177 "lex.l"


int yywrap(void)
{
	puts("--------the file is end");
	return 1;
}

